// Copyright (c) 2026 ThinkStudio LLC. All rights reserved.
// Licensed under the MIT License.

use std::path::{Path, PathBuf};
use std::time::Instant;

use tlbus_core::{
    BusError, BusFrame, Daemon, DaemonConfig, Envelope, FederationConfig, PluginContext, PluginContextFactory,
    PluginContextExt, PluginContextFactoryExt, PluginContextExt, PluginContextFactoryExt, PluginContextExt,
    PluginContextFactoryExt, PluginContextExt, PluginContextFactoryExt, PluginContextExt, PluginContextFactoryExt,
    PluginContextExt, PluginContextFactoryExt, PluginContextExt, PluginContextFactoryExt, PluginContextExt,
    PluginContextFactoryExt, PluginContextExt, PluginContextFactoryExt, PluginContextExt, PluginContextFactoryExt,
    PluginContextExt, PluginContextFactoryExt, PluginContextExt, PluginContextFactoryExt, PluginContextExt,
    PluginContextFactoryExt, PluginContextExt, PluginContextFactoryExt, PluginContextExt, PluginContextFactoryExt,
    PluginContextExt, PluginContextFactoryExt, PluginContextExt, PluginContextFactoryExt, PluginContextExt,
    PluginContextFactoryExt, PluginContextExt, PluginContextFactoryExt, PluginContextExt, PluginContextFactoryExt,
    PluginContextExt, PluginContextFactoryExt, PluginContextExt, PluginContextFactoryExt, PluginContextExt,
    PluginContextFactoryExt, PluginContextExt, PluginContextFactoryExt, PluginContextExt, PluginContextFactoryExt,
    PluginContextExt, PluginContextFactoryExt, PluginContextExt, PluginContextFactoryExt, PluginContextExt,
    PluginContextFactoryExt, PluginContextExt, PluginContextFactoryExt, PluginContextExt, PluginContextFactoryExt,
    PluginContextExt, PluginContextFactoryExt, PluginContextExt, PluginContextFactoryExt, PluginContextExt,
    PluginContextFactoryExt, PluginContextExt, PluginContextFactoryExt, PluginContextExt, PluginContextFactoryExt,
    PluginContextExt, PluginContextFactoryExt, PluginContextExt, PluginContextFactoryExt, PluginContextExt,
    PluginContextFactoryExt, PluginContextExt, PluginContextFactoryExt, PluginContextExt, PluginContextFactoryExt,
    PluginContextExt, PluginContextFactoryExt, PluginContextExt, PluginContextFactoryExt, PluginContextExt,
    PluginContextFactoryExt, PluginContextExt, PluginContextFactoryExt, PluginContextExt, PluginContextFactoryExt,
    PluginContextFactoryExt, PluginContextExt, PluginContextFactoryExt, PluginContextExt, PluginContextFactoryExt,
    PluginContextFactoryExt, PluginContextExt, PluginContextFactoryExt, PluginContextExt, PluginContextFactoryExt,
    PluginContextFactoryExt, PluginContextExt, PluginContextFactoryExt, PluginContextExt, PluginContextFactoryExt,
    PluginContextFactoryExt, PluginContextExt, PluginContextFactoryExt, PluginContextExt, PluginContextFactoryExt,
    PluginContextFactoryExt, PluginContextExt, PluginContextFactoryExt, PluginContextExt, PluginContextFactoryExt,
    PluginContextFactoryExt, PluginContextExt, PluginContextFactoryExt, PluginContextExt, PluginContextFactoryExt,
    PluginContextFactoryExt, PluginContextExt, PluginContextFactoryExt, PluginContextExt, PluginContextFactoryExt,
    PluginContextFactoryExt, PluginContextExt, PluginContextFactoryExt, PluginContextExt, PluginContextFactoryExt,
    PluginContextFactoryExt, PluginContextExt, PluginContextFactoryExt, PluginContextExt, PluginContextFactoryExt,
    PluginContextFactoryExt, PluginContextExt, PluginContextFactoryExt, PluginContextExt, PluginContextFactoryExt,
    PluginContextFactoryExt, PluginContextExt, PluginContextFactoryExt, PluginContextExt, PluginContextFactoryExt,
    PluginContextFactoryExt, PluginContextExt, PluginContextFactoryExt, PluginContextExt, PluginContextFactoryExt,
    PluginContextFactoryExt, PluginContextExt, PluginContextFactoryExt, PluginContextExt, PluginContextFactoryExt,
    PluginContextFactoryExt, PluginContextExt, PluginContextFactoryExt, PluginContextExt, PluginContextFactoryExt,
    PluginContextFactoryExt, PluginContextExt, PluginContextFactoryExt, PluginContextExt, PluginContextFactoryExt,
    PluginContextFactoryExt, PluginContextExt, PluginContextFactoryExt, PluginContextExt, PluginContextFactoryExt,
    PluginContextFactoryExt, PluginContextExt, PluginContextFactoryExt, PluginContextExt, PluginContextFactoryExt,
    PluginContextFactoryExt, PluginContextExt, PluginContextFactoryExt, PluginContextExt, PluginContextFactoryExt,
    PluginContextFactoryExt, PluginContextExt, PluginContextFactoryExt, PluginContextExt, PluginContextFactoryExt,
